In [2]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

# Load dataset
X, y = load_wine(return_X_y=True)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
print(np.sqrt(np.square(X_train[:] - X_test[1])))

X_train shape: (124, 13)
X_test shape: (54, 13)
y_train shape: (124,)
y_test shape: (54,)
[[1.58e+00 2.80e-01 1.20e-01 ... 3.00e-01 6.70e-01 9.65e+02]
 [1.56e+00 5.00e-02 1.70e-01 ... 2.60e-01 4.80e-01 9.30e+02]
 [1.11e+00 1.90e-01 3.10e-01 ... 3.60e-01 5.50e-01 5.25e+02]
 ...
 [9.40e-01 4.50e-01 2.20e-01 ... 8.40e-01 9.00e-01 7.00e+01]
 [8.00e-02 3.27e+00 1.00e-02 ... 7.00e-01 9.60e-01 3.65e+02]
 [4.70e-01 9.00e-02 5.10e-01 ... 4.70e-01 6.40e-01 9.50e+01]]


In [3]:
wine = load_wine()

df = pd.DataFrame(wine.data, columns=wine.feature_names)
df["target"] = wine.target

#df.groupby('target').mean()
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2


In [4]:
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)

X_train_scaled = (X_train - mean) / std
X_test_scaled = (X_test - mean) / std

In [26]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
np.sum(np.sqrt(np.square(X_train_scaled[:] - X_test_scaled[1])),axis=1)

X_train shape: (124, 13)
X_test shape: (54, 13)
y_train shape: (124,)
y_test shape: (54,)


array([ 5.59785438,  7.51476806,  7.61406079,  7.64919173,  7.91187993,
        8.13689207,  8.25920654,  8.26371513,  8.395475  ,  8.40237008,
        8.53299354,  8.6874764 ,  9.2830203 ,  9.72458941,  9.91311966,
        9.92356018, 10.00414224, 10.13103223, 10.57483744, 10.68919671,
       10.69951844, 10.73391135, 10.83891392, 11.02740539, 11.2841158 ,
       11.30618115, 11.33359734, 11.3528545 , 11.35747738, 11.46191434,
       11.57312505, 11.60536905, 11.60960955, 11.70059149, 11.7139701 ,
       11.75562092, 11.78842671, 11.88734123, 11.89444523, 12.04210488,
       12.40048032, 12.4708739 , 12.48667961, 12.49606958, 12.55167479,
       12.64717066, 12.70372332, 12.72219587, 13.18638767, 13.42292024,
       13.50758476, 13.51940312, 13.67182801, 13.69809074, 13.71577657,
       13.74936457, 13.77430806, 13.8505151 , 14.01513201, 14.02638268,
       14.0661024 , 14.08957129, 14.11796106, 14.14628996, 14.20344663,
       14.29249822, 14.4076979 , 14.53981496, 14.75867753, 14.78